// GLOBAL
export const GET_EXAMPLE_SAGA = 'GET_EXAMPLE_SAGA' as const;
export const SET_GLOBAL_LEFT_MENU_IS_VISIBLE = 'SET_GLOBAL_LEFT_MENU_IS_VISIBLE' as const;
export const TOGGLE_GLOBAL_LEFT_MENU_IS_VISIBLE = 'TOGGLE_GLOBAL_LEFT_MENU_IS_VISIBLE' as const;
